[book]
title = "libinspector Documentation"
description = "libinspector is a Multi-purpose Linux memory manipulation and interaction crate."
authors = ["standard3"]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/docs/"
git-repository-url = "https://github.com/standard3/libinspector/tree/main/docs"
edit-url-template = "https://github.com/standard3/libinspector/edit/main/docs/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
